// <copyright file="SessionUris.cs" company="DECTech.Tokyo">
// Copyright (c) DECTech.Tokyo. All rights reserved.
// </copyright>

/*
 * Crawler API
 *
 * API for crawling web pages and searching in crowled result
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zakhar_amirov@dectech.tokyo
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace CrawlerApi.Models
{
    using System;
    using System.Runtime.Serialization;
    using System.Text;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Session URI and crawling state for it.
    /// </summary>
    [DataContract]
    public class SessionUri : IEquatable<SessionUri>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionUri" /> class.
        /// </summary>
        /// <param name="uri">Uri.</param>
        /// <param name="state">State.</param>
        public SessionUri(string uri = null, SessionState state = 0)
        {
            Uri = uri;
            State = state;
        }

        /// <summary>
        /// Gets State
        /// </summary>
        [DataMember(Name = "state")]
        [JsonConverter(typeof(StringEnumConverter))]
        public SessionState State { get; }

        /// <summary>
        /// Gets Uri
        /// </summary>
        [DataMember(Name = "uri")]
        public string Uri { get; }

        /// <summary>Compare objects equality</summary>
        /// <param name="left">Left part of expression.</param>
        /// <param name="right">Right part of expression.</param>
        public static bool operator ==(SessionUri left, SessionUri right)
        {
            return Equals(left, right);
        }

        /// <summary>
        /// Compare objects unequality
        /// </summary>
        /// <param name="left">Left part of expression.</param>
        /// <param name="right">Right part of expression.</param>
        public static bool operator !=(SessionUri left, SessionUri right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj.GetType() != GetType())
            {
                return false;
            }

            return Equals((SessionUri)obj);
        }

        /// <summary>
        /// Returns true if SessionUris instances are equal
        /// </summary>
        /// <param name="other">Instance of SessionUris to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SessionUri other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    (Uri == other.Uri) ||
                    ((Uri != null) &&
                     Uri.Equals(other.Uri))) &&
                (
                    (State == other.State) ||
                    State.Equals(other.State));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked
            {
                var hash = 41;

                // Suitable nullity checks etc, of course :)
                if (Uri != null)
                {
                    hash = (hash * 59) + Uri.GetHashCode();
                }

                hash = (hash * 59) + State.GetHashCode();

                return hash;
            }
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SessionUris {\n");
            sb.Append("  Uri: ").Append(Uri).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}