/*
 * Crawler API
 *
 * API for crawling web pages and searching in crowled result
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zakhar_amirov@dectech.tokyo
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// crawled page content request parameters.
    /// </summary>
    [DataContract]
    public partial class GetPageParameters :  IEquatable<GetPageParameters>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPageParameters" /> class.
        /// </summary>
        /// <param name="OwnerId">id used to keep history of requests and blobs collection.</param>
        /// <param name="Uri">uri to retreive.</param>
        public GetPageParameters(string OwnerId = null, string Uri = null)
        {
            this.OwnerId = OwnerId;
            this.Uri = Uri;
            
        }

        /// <summary>
        /// id used to keep history of requests and blobs collection
        /// </summary>
        /// <value>id used to keep history of requests and blobs collection</value>
        [DataMember(Name="ownerId")]
        public string OwnerId { get; }

        /// <summary>
        /// uri to retreive
        /// </summary>
        /// <value>uri to retreive</value>
        [DataMember(Name="uri")]
        public string Uri { get; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetPageParameters {\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  Uri: ").Append(Uri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((GetPageParameters)obj);
        }

        /// <summary>
        /// Returns true if GetPageParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of GetPageParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetPageParameters other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OwnerId == other.OwnerId ||
                    OwnerId != null &&
                    OwnerId.Equals(other.OwnerId)
                ) && 
                (
                    Uri == other.Uri ||
                    Uri != null &&
                    Uri.Equals(other.Uri)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (OwnerId != null)
                    hash = hash * 59 + OwnerId.GetHashCode();
                if (Uri != null)
                    hash = hash * 59 + Uri.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(GetPageParameters left, GetPageParameters right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetPageParameters left, GetPageParameters right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
