/*
 * Crawler API
 *
 * API for crawling web pages and searching in crowled result
 *
 * OpenAPI spec version: 1.0.0
 * Contact: zakhar_amirov@dectech.tokyo
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// paging request parameters
    /// </summary>
    [DataContract]
    public partial class Page :  IEquatable<Page>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Page" /> class.
        /// </summary>
        /// <param name="PageStart">index of item to start page. if missing starts from 0..</param>
        /// <param name="PageSize">number of items to return in one request. if missing returns 10 items..</param>
        /// <param name="RequestId">id of paged request to keep paging between requests. if missing starts new request..</param>
        public Page(int? PageStart = null, int? PageSize = null, string RequestId = null)
        {
            this.PageStart = PageStart;
            this.PageSize = PageSize;
            this.RequestId = RequestId;
            
        }

        /// <summary>
        /// index of item to start page. if missing starts from 0.
        /// </summary>
        /// <value>index of item to start page. if missing starts from 0.</value>
        [DataMember(Name="pageStart")]
        public int? PageStart { get; }

        /// <summary>
        /// number of items to return in one request. if missing returns 10 items.
        /// </summary>
        /// <value>number of items to return in one request. if missing returns 10 items.</value>
        [DataMember(Name="pageSize")]
        public int? PageSize { get; }

        /// <summary>
        /// id of paged request to keep paging between requests. if missing starts new request.
        /// </summary>
        /// <value>id of paged request to keep paging between requests. if missing starts new request.</value>
        [DataMember(Name="requestId")]
        public string RequestId { get; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Page {\n");
            sb.Append("  PageStart: ").Append(PageStart).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Page)obj);
        }

        /// <summary>
        /// Returns true if Page instances are equal
        /// </summary>
        /// <param name="other">Instance of Page to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Page other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PageStart == other.PageStart ||
                    PageStart != null &&
                    PageStart.Equals(other.PageStart)
                ) && 
                (
                    PageSize == other.PageSize ||
                    PageSize != null &&
                    PageSize.Equals(other.PageSize)
                ) && 
                (
                    RequestId == other.RequestId ||
                    RequestId != null &&
                    RequestId.Equals(other.RequestId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (PageStart != null)
                    hash = hash * 59 + PageStart.GetHashCode();
                if (PageSize != null)
                    hash = hash * 59 + PageSize.GetHashCode();
                if (RequestId != null)
                    hash = hash * 59 + RequestId.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Page left, Page right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Page left, Page right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
